# config/config.yaml

default: &default
  app_name: "Random Code Name Generator"
  debug: true
  database:
    uri: "sqlite:///dev_code_names.db"

development:
  <<: *default
  environment: "developmnt"  
  database:
    uri: "sqlite:///dev_code_names.db" 

production:
  <<: *default
  environment: "production"
  debug: False 
  datbase: 
    uri: "sqlite:///prod_code_names.db" 
