name: Python Application

on:
  push:
    branches:
      - main
      - dev-branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt   

    # Hardcoded password in the curl command (bad practice)
    - name: Send password via curl to open endpoint (bad practice)
      run: |
        curl -X POST https://httpbin.org/post \
        -H 'Content-Type: application/json' \
        -d '{"username":"admin","password":"supersecretpassword123"}'
    
    # Weak cryptographic algorithm (MD5) used for hashing (bad practice)
    - name: Weak Cryptographic Algorithm (MD5)
      run: |
        echo "Using weak cryptographic algorithm MD5 to hash a password"
        echo -n "supersecretpassword123" | md5sum

    # Hardcoded API key with curl to an open endpoint (bad practice)
    - name: Send API key via curl to open endpoint (bad practice)
      run: |
        curl -X GET "http://example.com/api/data" \
        -H "Authorization: Bearer 1234567890abcdef"

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest
